### ISSUE TITLE
kok wai add new task list

### ISSUE THREAD

**Issue by natagowai** [githubschool/exactly-october#15]
##natagowai## will choose an image, add a caption, and add both to a file.

- [ ] Create a branch
- [ ] Edit the file
- [ ] Commit the changes
- [ ] Create a Pull Request
- [ ] Request a Review
- [ ] Make more changes
- [ ] Get an approval
- [ ] Merge the Pull Request
